- id: cargo-sort
  name: Ensure Cargo.toml is sorted
  entry: cargo-sort
  language: rust
  types: [file, toml]
  files: Cargo\.toml
  pass_filenames: false

- id: cargo-sort-workspace-grouped
  name: Ensure Cargo.toml is sorted
  entry: cargo-sort --workspace --groups
  language: rust
  types: [file, toml]
  files: Cargo\.toml
  pass_filenames: false
